"""add groups

Revision ID: 1edc5b33962a
Revises: 2460bc677157
Create Date: 2024-06-28 21:58:59.897219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1edc5b33962a'
down_revision = '2460bc677157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_seen',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_user_last_seen'), ['last_seen'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_last_seen'))
        batch_op.alter_column('last_seen',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
